version: '3.8'

services:
  webp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: image-webp-service
    ports:
      - "3000:3000"
    volumes:
      - ./files:/app/files
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/health" ]
      interval: 10s
      timeout: 3s
      retries: 3
